# Generated by Django 6.0.1 on 2026-01-28 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAdditionals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('location', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('college_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.TextField(blank=True, null=True)),
                ('study_field', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.TextField(blank=True, null=True)),
                ('end_year', models.TextField(blank=True, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=10, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('certificate_url', models.TextField(blank=True, null=True)),
                ('additional_skills', models.JSONField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_additionals',
                'managed': True,
            },
        ),
    ]
