# Generated by Django 6.0.1 on 2026-02-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='useradditionals',
            name='certificate_url',
        ),
        migrations.AddField(
            model_name='user',
            name='usage_count',
            field=models.JSONField(default=dict),
        ),
    ]
